server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    add_header Cross-Origin-Opener-Policy "same-origin-allow-popups";
    try_files $uri $uri/ /index.html;
  }
}
