services:
  postgres:
    image: postgres:16-alpine
    container_name: school_postgres
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school_net

  backend:
    build: ./backend
    container_name: school_backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/school_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET}
      SYSTEM_ADMIN_EMAIL: ${SYSTEM_ADMIN_EMAIL}
      SYSTEM_ADMIN_PASSWORD: ${SYSTEM_ADMIN_PASSWORD}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_APP_PASSWORD: ${MAIL_APP_PASSWORD}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
    depends_on:
      - postgres
    networks:
      - school_net

  frontend:
    build: ./frontend
    container_name: school_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - school_net

volumes:
  postgres_data:


networks:
  school_net:
    driver: bridge
